= ★ easyletter -- _for easy letters_ ★

== Introduction

easyletter allows you to create simple, formal documents, which are oriented at DIN 5008, although not strictly complying to that norm. The main goals of this tool are:

* Make the creation of simple letters for every-day-use very easy
* Letters should fit into normal envelopes with window
* Produce a cross-platform output (PDF)

== Install & Use

The tool is Python based and can be installed and run with `pipenv`.

[source, shell]
----
$ pipenv run python easyletter.py in/sample.yml
----

You can modify the content of the letter by customizing either the provided YAML file or by creating a new file

== Configurations

All relevant configurations can be looked up in `in/sample.yml`.

=== Contact section

In the `contact` section, you can add arbitrary properties.
All properties will be printed in a box to the right, directly below the sender address.
The property key will be printed out, so they can be escaped with single quotes, e.g.:

[source, yaml]
----
contact:
  'Item 1': Text for item 1
----

will be printed out as

> Item 1: Text for item 1

=== Date

The date, which is printed in the letter, will be automatically formatted with the system default language format for dates/time.
The used locale can be customized, e.g.:

[source, yaml]
----
locale: en_US
----

=== Ending

If an `ending` is provided, it will be printed below the content.
After the ending, the name of the sender will be printed with a certain margin to the top so that the signature can be placed between.
